version: '3.8'
services:
  flask:
    build: .
    ports:
      - "5780:5000"
    volumes:
      - ./dashboard:/app/dashboard
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=mydatabase
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8057:80"
    environment:
      - PMA_ARBITRARY=1
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.74.0/24
