version: '3'

services:
  flask:
    build: .
    image: mycard
    container_name: mycard
    restart: unless-stopped
    ports:
      - "5555:5000"
    depends_on:
      - mysql-db'

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: btph
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ''
    depends_on:
      - mysql-db
